### ISSUE TITLE
Issue running with  --enable-source-maps

### ISSUE THREAD

**Issue by sfarthin** [steelbrain/babel-cli#156]
![image](https://user-images.githubusercontent.com/516498/95081458-90b62400-06e7-11eb-91e8-6d0c4c554f2f.png)

^^ I am not able to use `--enable-source-maps` currently. Am I doing something wrong?

**Comment by steelbrain** [comment]
commander’s upgrade bit back, expect a fix soon

**Comment by steelbrain** [comment]
Fixed v3.1.1
