### ISSUE TITLE
iterate.js missing from 3.1.1

### ISSUE THREAD

**Issue by sfarthin** [steelbrain/babel-cli#157]
![image](https://user-images.githubusercontent.com/516498/95202784-c7f00800-07af-11eb-8931-e0481407819c.png)

**Comment by steelbrain** [comment]
Super embarrassing. I'm so sorry 😬
Fixing

**Comment by sfarthin** [comment]
no worries

**Comment by steelbrain** [comment]
v3.1.2 is out with the fix!
